apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200