apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-local-storage-pv
spec:
  storageClassName: elasticsearch-local-storage
  capacity:
    storage: 800Mi
  hostPath:
    path: /mnt/data/elasticsearch/
  accessModes:
    - ReadWriteMany