apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.0.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch-service:9200"
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
          resources:
            requests:
              memory: "600Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "600m"   