FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app
COPY . .

# Restore dependencies
RUN dotnet restore src/Movements.AsyncReceiver

# Publish project
RUN dotnet publish src/Movements.AsyncReceiver -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Movements.AsyncReceiver.dll"]