apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-local-storage-pv
spec:
  storageClassName: postgres-local-storage
  capacity:
    storage: 700Mi
  hostPath:
    path: /mnt/data/postgres/
  accessModes:
    - ReadWriteMany