apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    component: postgres
spec:
  clusterIP: None
  selector:    
      component: postgres
  ports:
  - port: 5432
    targetPort: 5432
